language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test —prefix frontend
  - npm run build —prefix frontend
deploy:
provider: heroku
project: ./build/
on:
  branch: main
