export const RECEIPT_LIST_REQUEST = "RECEIPT_LIST_REQUEST"
export const RECEIPT_LIST_SUCCESS = "RECEIPT_LIST_SUCCESS"
export const RECEIPT_LIST_FAIL = "RECEIPT_LIST_FAIL"

export const RECEIPT_DETAILS_REQUEST = "RECEIPT_DETAILS_REQUEST"
export const RECEIPT_DETAILS_SUCCESS = "RECEIPT_DETAILS_SUCCESS"
export const RECEIPT_DETAILS_FAIL = "RECEIPT_DETAILS_FAIL"

export const FAVOURITES_ADD_ITEM = "FAVOURITES_ADD_ITEM"
export const FAVOURITES_REMOVE_ITEM = "FAVOURITES_REMOVE_ITEM"